apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: demo-devops-hpa
  namespace: demo-devops
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: demo-devops
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
