name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up gcloud CLI
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up gcloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: devsu-devops-466116

      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: gke-standard-cluster
          location: us-central1-a
          project_id: devsu-devops-466116

      - name: Render deployment.yaml
        run: |
          envsubst < infra/manifests/deployment.tpl.yaml > infra/manifests/deployment.yaml

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f infra/manifests/configmaps/configmap.yaml
          kubectl apply -f infra/manifests/secrets/secret.yaml
          kubectl apply -f infra/manifests/deployment.yaml
          kubectl apply -f infra/manifests/service.yaml
          kubectl apply -f infra/manifests/hpa.yaml || echo "No HPA found, skipping..."

      - name: Check rollout status
        run: |
          kubectl rollout status deployment/demo-devops -n demo-devops
