name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    env:
      DJANGO_SETTINGS_MODULE: demo.settings
      DEBUG: false
      DATABASE_NAME: db.sqlite3
      DJANGO_SECRET_KEY: dummy-for-ci
      ALLOWED_HOSTS: localhost,127.0.0.1

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r devsu-demo-devops-python/requirements.txt
        pip install flake8 coverage

    - name: Run database migrations
      run: python devsu-demo-devops-python/manage.py migrate

    - name: Lint code with flake8
      run: flake8 devsu-demo-devops-python/

    - name: Run tests with coverage
      run: |
        coverage run devsu-demo-devops-python/manage.py test
        coverage report

    - name: Build Docker image
      run: docker build -t devsu-app .

    - name: Login to Docker Hub
      if: github.ref == 'refs/heads/main'
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Tag and Push image to Docker Hub
      if: github.ref == 'refs/heads/main'
      run: |
        IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/devsu-app:latest
        docker tag devsu-app $IMAGE
        docker push $IMAGE